import type { NotificationReasonCode } from "@/domain/notification";

export const NOTIFICATION_REASON_CODES: readonly NotificationReasonCode[] = [
  "SEND_TRIGGER_CRITICAL",
  "SEND_FOLLOW_UP_DUE",
  "SEND_PERSISTENT_REPEAT",
  "DEFER_QUIET_HOURS",
  "DEFER_WORKING_HOURS",
  "DEFER_WEEKEND",
  "SUPPRESS_COOLDOWN",
  "SUPPRESS_ENTITY_FATIGUE",
  "SUPPRESS_GLOBAL_FATIGUE",
  "SUPPRESS_ALREADY_RESOLVED",
  "SUPPRESS_DUPLICATE",
  "SCHEDULE_RELATIVE_REMINDER",
  "ESCALATED_DEADLINE",
  "ESCALATED_OVERDUE",
  "ESCALATED_REPEATED_SNOOZE",
  "ESCALATED_PERSISTENT_UNRESOLVED",
  "ESCALATED_FINANCIAL_DUE",
  "DEGRADED_PLATFORM_CAPABILITY",
  "CANCEL_SOURCE_COMPLETED",
  "EXPIRED",
];
