export const PLANNER_REASON_CODES = {
  HIGH_PRIORITY: "HIGH_PRIORITY",
  HARD_DEADLINE_FIT: "HARD_DEADLINE_FIT",
  PLANNED_TODAY: "PLANNED_TODAY",
  EXACT_WINDOW_FIT: "EXACT_WINDOW_FIT",
  CHUNK_FIT: "CHUNK_FIT",
  PRESERVED_EXISTING_BLOCK: "PRESERVED_EXISTING_BLOCK",
  MOVED_DUE_TO_CONFLICT: "MOVED_DUE_TO_CONFLICT",
  UNSCHEDULED_NO_ESTIMATE: "UNSCHEDULED_NO_ESTIMATE",
  UNSCHEDULED_NO_FIT: "UNSCHEDULED_NO_FIT",
  LOCKED_BLOCK_CONFLICT: "LOCKED_BLOCK_CONFLICT",
  ESTIMATE_REQUIRED: "ESTIMATE_REQUIRED",
} as const;
