/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as ShareSettingsRouteImport } from './routes/share-settings'
import { Route as ShareInboxRouteImport } from './routes/share-inbox'
import { Route as ShareAnalyticsRouteImport } from './routes/share-analytics'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as KeepRouteImport } from './routes/keep'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BorsaRouteImport } from './routes/borsa'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSettingsRoute = ShareSettingsRouteImport.update({
  id: '/share-settings',
  path: '/share-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareInboxRoute = ShareInboxRouteImport.update({
  id: '/share-inbox',
  path: '/share-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareAnalyticsRoute = ShareAnalyticsRouteImport.update({
  id: '/share-analytics',
  path: '/share-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const KeepRoute = KeepRouteImport.update({
  id: '/keep',
  path: '/keep',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BorsaRoute = BorsaRouteImport.update({
  id: '/borsa',
  path: '/borsa',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/borsa': typeof BorsaRoute
  '/calendar': typeof CalendarRoute
  '/keep': typeof KeepRoute
  '/pulse': typeof PulseRoute
  '/share-analytics': typeof ShareAnalyticsRoute
  '/share-inbox': typeof ShareInboxRoute
  '/share-settings': typeof ShareSettingsRoute
  '/todos': typeof TodosRoute
  '/unlock': typeof UnlockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/borsa': typeof BorsaRoute
  '/calendar': typeof CalendarRoute
  '/keep': typeof KeepRoute
  '/pulse': typeof PulseRoute
  '/share-analytics': typeof ShareAnalyticsRoute
  '/share-inbox': typeof ShareInboxRoute
  '/share-settings': typeof ShareSettingsRoute
  '/todos': typeof TodosRoute
  '/unlock': typeof UnlockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/borsa': typeof BorsaRoute
  '/calendar': typeof CalendarRoute
  '/keep': typeof KeepRoute
  '/pulse': typeof PulseRoute
  '/share-analytics': typeof ShareAnalyticsRoute
  '/share-inbox': typeof ShareInboxRoute
  '/share-settings': typeof ShareSettingsRoute
  '/todos': typeof TodosRoute
  '/unlock': typeof UnlockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/borsa'
    | '/calendar'
    | '/keep'
    | '/pulse'
    | '/share-analytics'
    | '/share-inbox'
    | '/share-settings'
    | '/todos'
    | '/unlock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/borsa'
    | '/calendar'
    | '/keep'
    | '/pulse'
    | '/share-analytics'
    | '/share-inbox'
    | '/share-settings'
    | '/todos'
    | '/unlock'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/borsa'
    | '/calendar'
    | '/keep'
    | '/pulse'
    | '/share-analytics'
    | '/share-inbox'
    | '/share-settings'
    | '/todos'
    | '/unlock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  BorsaRoute: typeof BorsaRoute
  CalendarRoute: typeof CalendarRoute
  KeepRoute: typeof KeepRoute
  PulseRoute: typeof PulseRoute
  ShareAnalyticsRoute: typeof ShareAnalyticsRoute
  ShareInboxRoute: typeof ShareInboxRoute
  ShareSettingsRoute: typeof ShareSettingsRoute
  TodosRoute: typeof TodosRoute
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-settings': {
      id: '/share-settings'
      path: '/share-settings'
      fullPath: '/share-settings'
      preLoaderRoute: typeof ShareSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-inbox': {
      id: '/share-inbox'
      path: '/share-inbox'
      fullPath: '/share-inbox'
      preLoaderRoute: typeof ShareInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-analytics': {
      id: '/share-analytics'
      path: '/share-analytics'
      fullPath: '/share-analytics'
      preLoaderRoute: typeof ShareAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keep': {
      id: '/keep'
      path: '/keep'
      fullPath: '/keep'
      preLoaderRoute: typeof KeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borsa': {
      id: '/borsa'
      path: '/borsa'
      fullPath: '/borsa'
      preLoaderRoute: typeof BorsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  BorsaRoute: BorsaRoute,
  CalendarRoute: CalendarRoute,
  KeepRoute: KeepRoute,
  PulseRoute: PulseRoute,
  ShareAnalyticsRoute: ShareAnalyticsRoute,
  ShareInboxRoute: ShareInboxRoute,
  ShareSettingsRoute: ShareSettingsRoute,
  TodosRoute: TodosRoute,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
